apiVersion: v1
kind: ConfigMap
metadata:
  name: signboard-config
  namespace: default
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
  SPRING_JPA_OPEN_IN_VIEW: "false"
  SPRING_APPLICATION_NAME: "SignBoard"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_POOL_NAME: "SignBoardHikariPool"
  CANVA_API_REDIRECT_URI: "http://your-domain.com/login/oauth2/code/canva"
  CANVA_API_RETURN_URI: "http://your-domain.com/return"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CANVA_REDIRECT_URI: "http://your-domain.com/login/oauth2/code/canva"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CANVA_AUTHORIZATION_GRANT_TYPE: "authorization_code"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CANVA_SCOPE: "design:content:write,design:meta:read,design:content:read"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_CANVA_AUTHORIZATION_URI: "https://www.canva.com/api/oauth/authorize"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_CANVA_TOKEN_URI: "https://api.canva.com/v1/oauth/token"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_CANVA_USER_INFO_URI: "https://api.canva.com/v1/user"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_CANVA_USER_NAME_ATTRIBUTE: "sub"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "http://your-domain.com/login/oauth2/code/google"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: "openid,email,profile"
  application.frontend.url: "https://ai2.vn"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "DEBUG"
  LOGGING_LEVEL_COM_TECHBYTEDEV: "DEBUG"
  UPLOAD_DIR: "src/main/resources/static/images"
  springdoc.api-docs.enabled: "true"
  springdoc.swagger-ui.enabled: "true"
  springdoc.swagger-ui.path: "/swagger-ui.html"
  springdoc.packagesToScan: "com.techbytedev.signboardmanager.controller"
  springdoc.pathsToMatch: "/api/**"
  spring.data.web.pageable.one-indexed-parameters: "true"
  springdoc.default-produces-media-type: "application/json"
  springdoc.default-consumes-media-type: "application/json"