apiVersion: v1
kind: Secret
metadata:
  name: ai2-secret
  namespace: ai2
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2U6MzMwNi9obGNmd3Jld2hvc3Rpbmdfc2lnbi1ib2FyZD91c2VTU0w9ZmFsc2Umc2VydmVyVGltZXpvbmU9VVRDJmNoYXJhY3RlckVuY29kaW5nPVVURi04JnVzZVVuaWNvZGU9dHJ1ZQ==
  SPRING_DATASOURCE_USERNAME: YWkyX3VzZXJuYW1lX3RlY2hieXRl
  SPRING_DATASOURCE_PASSWORD: YWkyX25ld3Bhc3N3b3JkX3RlY2hieXRl
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy
  SPRING_MAIL_USERNAME: YWlAaWRhaS52bg==
  SPRING_MAIL_PASSWORD: bWp5cSBma3RvIHFyYWggZ2Rvbg==
  JWT_SECRET: eW91cl92ZXJ5X2xvbmdfYW5kX3NlY3VyZV9qd3Rfc2VjcmV0X2tleV8zMl9ieXRlc19taW5pbXVt
  CANVA_API_KEY: T0MtQVpaNkw5X0pXZVEwNg==
  CANVA_API_SECRET: Y252Y2EwaVR3NGxsSmxIWEU2aXFwVlI2R09EVEU2Y2I0c1ZweEVkbi1acGtXeWwwOWQ3OTIzMWU=
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CANVA_CLIENT_ID: T0MtQVpaNkw5X0pXZVEwNg==
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CANVA_CLIENT_SECRET: Y252Y2EwaVR3NGxsSmxIWEU2aXFwVlI2R09EVEU2Y2I0c1ZweEVkbi1acGtXeWwwOWQ3OTIzMWU=
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: OTk0ODQwMjkxNDE4LTNqcnY3c3F0Yjlsb3I1b3JxNWcyOWw0MDA4aWVraXZwLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: R09DU1BYLVVnSnNnSXVNUkxya2JHSWJiNDlKWkR5RnRkU1I=