apiVersion: v1
kind: Service
metadata:
  name: signboard-service
  namespace: default
spec:
  selector:
    app: signboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP